### ISSUE TITLE
pry cannot debug when fakefs is intercepting the filesystem

### ISSUE THREAD

**Issue by compwron** [fakefs/fakefs#362] opened 2017-01-19 11:32 UTC
When debugging a test, I see:
```
✗ rspec spec/my_spec.rb
[1] pry(#<RSpec::ExampleGroups::MyClass::MyTest>)> 
[2] pry(#<RSpec::ExampleGroups::MyClass::MyTest>)> ls
[1] pry(#<RSpec::ExampleGroups::MyClass::MyTest>)> ls
[2] pry(#<RSpec::ExampleGroups::MyClass::MyTest>)> wtf?

Failures:

  1) my test name
     Failure/Error: binding.pry
     
     Errno::ENOENT:
       No such file or directory - /Users/me/.pry_history
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/fakefs-0.10.2/lib/fakefs/file.rb:654:in `create_missing_file'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/fakefs-0.10.2/lib/fakefs/file.rb:410:in `initialize'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/history.rb:114:in `open'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/history.rb:114:in `history_file'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/history.rb:106:in `save_to_file'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/history.rb:50:in `call'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/history.rb:50:in `push'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/pry_instance.rb:267:in `handle_line'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/pry_instance.rb:242:in `catch'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/pry_instance.rb:242:in `block in eval'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/pry_instance.rb:241:in `catch'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/pry_instance.rb:241:in `eval'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/repl.rb:77:in `block in repl'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/repl.rb:67:in `loop'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/repl.rb:67:in `repl'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/repl.rb:38:in `block in start'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/input_lock.rb:61:in `__with_ownership'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/input_lock.rb:79:in `with_ownership'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/repl.rb:38:in `start'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/repl.rb:15:in `start'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/pry_class.rb:169:in `start'
     # /Users/me/.rvm/gems/ruby-2.4.0-rc1/gems/pry-0.10.4/lib/pry/core_extensions.rb:43:in `pry'
     # ./spec/my_spec.rb:54:in `block (3 levels) in <top (required)>'
```

It seems pretty clear that pry cannot operate when ~/.pry_history is inaccessible (for example, when fakefs is intercepting the filesystem)

Since I use fakefs in my test, this is really inconvenient. Has anyone else had this problem? Can anyone think of a way around it, other than not debugging, or changing all of my tests?

reference: https://github.com/pry/pry/issues/1593

**Comment by grosser** [comment] 2017-01-19 15:51
pry should simply not fail when the file is missing, so I think there is
some deeper issue in pry where it uses some method of checking that fakefs
did not stub ... if you find that we can figure out how to stub that ...

**Comment by asterr** [comment] 2017-04-11 06:17
My work around was to disable load and save of pry history:

require 'pry'
Pry.config.history.should_load = false
Pry.config.history.should_save = false

**Comment by ryanmattcollins** [comment] 2017-06-15 19:50
We encountered this issue as well. It manifested as some weird `byebug9.0.6 gemspec is missing or broken` error. My theory is that `pry` relies on `File` or `FileUtils` and fails while FakeFS is active because it hijacks calls to those.

**Comment by asterr** [comment] 2017-06-16 00:16
@ryanmattcollins -- I also came to the conclusion that the problem was Pry attempting to use File and FileUtils, which are hijacked by design.  Hence my work around to disable history, which seems to alleviate the problem.

**Comment by kmcphillips** [comment] 2018-02-12 22:12
I fixed this in pry, so you can close this issue now I believe.

**Closed** 2018-02-13 17:16 UTC
