### ISSUE TITLE
Errno::ENOENT: No such file or directory

### ISSUE THREAD

**Issue by volkanunsal** [fakefs/fakefs#310] opened 2015-06-28 23:09 UTC
I am using FakeFS to capture the output Sprockets compilation. I thought this would be easy, but it hasn't been. The problem I am running into is for some reason FakeFS cannot find the fake file it created –– that is my guess. 

Here is the my terminal output:

``` bash
[2] pry(#<AssetFinder>)> output_dir = Rails.root.join("public/assets")
=> #<FakeFS::Pathname:/Users/newuser/w/citiesense/search/public/assets>
[3] pry(#<AssetFinder>)> output_dir.children
=> [#<FakeFS::Pathname:/Users/newuser/w/citiesense/search/public/assets/sample-a8866ad1c1fd36e33c8b25b41f1cf65b.js+>]
[4] pry(#<AssetFinder>)> manifest.compile(matcher)
Errno::ENOENT: No such file or directory - /Users/newuser/w/citiesense/search/public/assets/sample-a8866ad1c1fd36e33c8b25b41f1cf65b.js+
from /Users/newuser/.rvm/gems/ruby-2.1.5@citiesense_search/gems/fakefs-0.6.7/lib/fakefs/fileutils.rb:188:in `block in mv'
```

As you can see from line `[3]`, the file seems to be in the file system, but `fakefs/fileutils.rb:188` doesn't think so. This is the code that throws that error:

``` ruby
if (target = FileSystem.find(path))
  dest_path = if File.directory?(dest)
                File.join(dest, File.basename(path))
              else
                dest
              end
  if File.directory?(dest_path)
    fail Errno::EEXIST, dest_path unless options[:force]
  elsif File.directory?(File.dirname(dest_path))
    FileSystem.delete(dest_path)
    FileSystem.add(dest_path, target.entry.clone)
    FileSystem.delete(path)
  else
    fail Errno::ENOENT, dest_path unless options[:force]
  end
else
  fail Errno::ENOENT, path
end
```

Can anyone shed any light on why `FileSystem.find` is returning nil here?

**Comment by sometimesfood** [comment] 2015-06-29 10:16
This seems to be a duplicate of #133. Apparently `FileSystem.find` has problems with filenames containing a `+` character.

**Comment by gnikonorov** [comment] 2018-08-16 19:40
Hi @volkanunsal,

It seems like this is no longer an issue. I was able to find the file `sample-a8866ad1c1fd36e33c8b25b41f1cf65b.js+` using both `ruby` and `ruby` under `fakefs`. I am going to close out this issue since I can't reproduce it and it's old, but please do re-open it if I misunderstood you.

With `fakefs`:
```
~/projects/fakefs/.my_tests/test_issue_310 [master|…45]
15:38 $ cat file_with_plus_write.rb
require 'fakefs'

filename = 'sample-a8866ad1c1fd36e33c8b25b41f1cf65b.js+'
File.open(filename, 'w') { |file| file.write("Some content") }
exists = File.exist?(filename)
if exists then
  puts "File exists"
else
  puts "File does not exist"
end

filename = 'a8866ad1c1fd36e33c8b25b41f1cf65b.js+'
exists = File.exist?(filename)
if exists then
  puts "File exists"
else
  puts "File does not exist"
end

~/projects/fakefs/.my_tests/test_issue_310 [master|…45]
15:38 $ ruby file_with_plus_write.rb
File exists
File does not exist
~/projects/fakefs/.my_tests/test_issue_310 [master|…45]
15:38 $
```

Without `fakefs`:
```
~/projects/fakefs/.my_tests/test_issue_310 [master|…45]
15:39 $ cat file_with_plus_write.rb
#require 'fakefs'

filename = 'sample-a8866ad1c1fd36e33c8b25b41f1cf65b.js+'
File.open(filename, 'w') { |file| file.write("Some content") }
exists = File.exist?(filename)
if exists then
  puts "File exists"
else
  puts "File does not exist"
end

filename = 'a8866ad1c1fd36e33c8b25b41f1cf65b.js+'
exists = File.exist?(filename)
if exists then
  puts "File exists"
else
  puts "File does not exist"
end

~/projects/fakefs/.my_tests/test_issue_310 [master|…45]
15:39 $ ruby file_with_plus_write.rb
File exists
File does not exist
~/projects/fakefs/.my_tests/test_issue_310 [master|…46]
15:39 $
```

**Closed by gnikonorov** 2018-08-16 19:40 UTC
